name: My Workflow
on:
  workflow_dispatch:
  repository_dispatch:
    inputs:
      home:
        description: 'Home'
        required: true
      name:
        description: 'Name'
        required: true

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
    - name: Print Inputs
      run: |
        echo "Input 1: ${{ inputs.input1 }}"
        echo "Input 2: ${{ inputs.input2 }}"
