name: My Workflow
on:
  workflow_dispatch:
    inputs:
      home:
        description: 'Home'
        required: true
      name:
        description: 'Name'
        required: true

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
    - name: Print Inputs
      run: |
        echo "Home is: ${{ inputs.home }}"
        echo "Name is: ${{ inputs.name }}"
